CREATE TABLE IF NOT EXISTS doctors (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  speciality VARCHAR(50),
  phone_number VARCHAR(15) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  crm VARCHAR(20) UNIQUE NOT NULL,
  role VARCHAR(20) DEFAULT 'doctor' CHECK (role IN ('doctor', 'admin')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NULL
);